# Generated by Django 3.0.7 on 2020-08-06 10:45

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='Мета-тег Title')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=150, unique=True, verbose_name='URL')),
                ('h1', models.CharField(db_index=True, max_length=300, verbose_name='Заголовок h1')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Мета-тег description')),
                ('text', models.TextField(blank=True, db_index=True, verbose_name='Описание')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('pub_update', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogs.Categories', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Владелец')),
                ('image', models.ImageField(blank=True, upload_to='catalog/owner/img/', verbose_name='Изображение')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('pub_update', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владельцы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название товара')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='Мета-тег Title')),
                ('h1', models.CharField(db_index=True, max_length=200, verbose_name='Заголовок h1')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=150, unique=True, verbose_name='URL')),
                ('description', models.CharField(max_length=300, null=True, verbose_name='Мета-тег description')),
                ('text', models.TextField(blank=True, db_index=True, verbose_name='Описание')),
                ('draft', models.BooleanField(help_text='Черновики не отображаются на сайте', verbose_name='Черновик')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('pub_update', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.Categories')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.Owner')),
            ],
            options={
                'verbose_name': 'Карточка питомца',
                'verbose_name_plural': 'Карточки питомца',
            },
        ),
    ]
