# Generated by Django 3.0.6 on 2020-05-26 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_title', models.CharField(max_length=300, verbose_name='Мета-тег Title')),
                ('categories_h1', models.CharField(max_length=300, verbose_name='Заголовок h1')),
                ('categories_description', models.CharField(max_length=400, verbose_name='Мета-тег description')),
                ('categories_text', models.TextField(verbose_name='Описание')),
                ('pub_date', models.DateTimeField(verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50, verbose_name='Владелец')),
                ('owner_email', models.CharField(max_length=200, verbose_name='Почта')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_h1', models.CharField(max_length=200, verbose_name='Заголовок h1')),
                ('product_text', models.TextField(verbose_name='Описание')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.Owner')),
            ],
        ),
    ]
