# Generated by Django 3.0.6 on 2020-05-27 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Владелец', 'verbose_name_plural': 'Владельцы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Карточка питомца', 'verbose_name_plural': 'Карточки питомца'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 21, 57, 53, 723717), verbose_name='Дата создания'),
        ),
    ]
