# Generated by Django 3.0.7 on 2020-08-07 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_auto_20200806_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображения питомца', 'verbose_name_plural': 'Изображения питомца'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='catalogs/product/img', verbose_name='Главная фотография'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.Categories', verbose_name='Категория'),
        ),
    ]
