# Generated by Django 3.0.7 on 2020-08-20 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_auto_20200807_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Дополнительные фотографии', 'verbose_name_plural': 'Дополнительные фотографии'},
        ),
        migrations.AddField(
            model_name='product',
            name='birthday',
            field=models.DateField(default='1996-06-28', verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='breed',
            field=models.CharField(blank=True, max_length=300, verbose_name='Порода'),
        ),
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.CharField(default='Девочка', max_length=10, verbose_name='Пол питомца'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='image',
            field=models.ImageField(blank=True, upload_to='catalogs/owner/img/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.Categories', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='catalogs/product/img', verbose_name='Дополнительные фотографии'),
        ),
    ]
