# Generated by Django 3.0.7 on 2020-08-26 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_auto_20200820_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='IP')),
                ('star', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Not Bad'), (4, 'Good'), (5, 'Very Good')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.Product', verbose_name='Питомец')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
    ]
