# Generated by Django 3.0.7 on 2020-08-27 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_auto_20200826_1429'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='RatingProduct',
        ),
    ]
