# Generated by Django 3.0.7 on 2020-09-09 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('catalogs', '0007_auto_20200827_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFlatPage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.FlatPage')),
            ],
            options={
                'verbose_name': 'Static Page',
            },
            bases=('flatpages.flatpage',),
        ),
        migrations.AlterField(
            model_name='ratingproduct',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Очень плохо'), (2, 'Плохо'), (3, 'Неплохо'), (4, 'Хорошо'), (5, 'Очень хорошо')], verbose_name='Рейтинг'),
        ),
    ]
