# Generated by Django 3.0.7 on 2020-09-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0008_auto_20200909_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='myflatpage',
            name='title1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
