# Generated by Django 3.0.7 on 2020-09-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0009_myflatpage_title1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyFlatPage',
        ),
    ]
