# Generated by Django 3.0.7 on 2020-09-17 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0001_initial'),
        ('catalogs', '0011_owner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.AddField(
            model_name='product',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lk.Profile', verbose_name='Владелец'),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
