# Generated by Django 3.0.7 on 2020-12-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0014_auto_20201118_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
