# Generated by Django 3.0.7 on 2020-10-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
