# Generated by Django 3.0.7 on 2020-09-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Адрес для рассылки', 'verbose_name_plural': 'Адреса для рассылки'},
        ),
    ]
